Gem::Specification.new do |s|
s.name        = 'tucubit'
s.version     = '0.1.2'
s.date        = '2014-08-16'
s.summary     = "tax script para tarjeta ciudadana"
s.description = "pago de bitcoins en pesos"
s.authors     = ["avilaroman"]
s.email       = 'avilaroman@gmail.com'
s.files       = Dir.['lib/*']#mejor que ["lib/imposition.rb"] etc
s.homepage    = 'https://github.com/avilaroman/tucubit'
end
